### PR TITLE
Kek/1.59.0

### PR DESCRIPTION
**Pull request by kristofferkoch**
I don't mean to merge this, rather force-push this into our develop branch.

### CODE REVIEW

**Review by antoinebardoz — APPROVED** [review]
I have no reason to believe this is wrong, but Geir is the one who's done this before.

Is the Jenkinsfile a new addition, or has it always been there?

**Comment by kristofferkoch** [comment]
> I have no reason to believe this is wrong, but Geir is the one who's done this before.
> 
> Is the Jenkinsfile a new addition, or has it always been there?

Always has been. I guess just one of these commits are changes to conan.

**Review by kaiaw — APPROVED** [review]
Don't think I have much to say on this, not familiar here. But if this is just updating the fork should be fine I guess?

**Comment by kristofferkoch** [comment]
Pushed into develop!

**Pull request closed without merging**
